In [1]:
import numpy as np
import pandas as pd

#### Creating a DataFrame

In [7]:
data = {
    'Name'   : ['Arijit', 'Pallabi', 'Anup', 'Indrani'],
    'Age'    : [38, 32, 75, 70],
    'City'   : ['Kolkata', 'Delhi', 'Chennai', 'Mumbai'],
    'Salary' : [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [23]:
datalist = [
    ['Arijit', 38, 'Kolkata', 65000],
    ['Pallabi', 32, 'Delhi', 70000],
    ['Anup', 75, 'Chennai', 62000],
    ['Indrani', 70, 'Mumbai', 85000]
]
columns = ['Name', 'Age', 'City', 'Salary']
dflist = pd.DataFrame(datalist, columns=columns)
dflist

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

#### Selection and Indexing of Columns

In [24]:
dflist['Name']

0     Arijit
1    Pallabi
2       Anup
3    Indrani
Name: Name, dtype: object

In [25]:
dflist[['City', 'Salary']]

      City  Salary
0  Kolkata   65000
1    Delhi   70000
2  Chennai   62000
3   Mumbai   85000

#### Creating a new column

In [26]:
dflist['Designation'] = ['CA', 'Doctor', 'Engineer', 'Doctor']
dflist

      Name  Age     City  Salary Designation
0   Arijit   38  Kolkata   65000          CA
1  Pallabi   32    Delhi   70000      Doctor
2     Anup   75  Chennai   62000    Engineer
3  Indrani   70   Mumbai   85000      Doctor

#### Removing Columns

In [27]:
dflist.drop(['Designation'], axis = 1, inplace=True)

In [21]:
dflist

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [28]:
dflist.drop([0], axis = 0)

      Name  Age     City  Salary
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

#### Selecting Rows

In [33]:
dflist

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [34]:
dflist.loc[[0, 1]]

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000

In [36]:
dflist.iloc[[2,3]]

      Name  Age     City  Salary
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

#### Selecting Subsets of Rows and Columns

In [37]:
dflist

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [42]:
dflist.loc[[0,1]][['City', 'Salary']]

      City  Salary
0  Kolkata   65000
1    Delhi   70000

In [43]:
dflist.loc[[2,3]][['Name', 'Age']]

      Name  Age
2     Anup   75
3  Indrani   70

#### Conditional Selection

In [44]:
dflist

      Name  Age     City  Salary
0   Arijit   38  Kolkata   65000
1  Pallabi   32    Delhi   70000
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [46]:
# I only want to see those people whose age is above 40
dflist[dflist['Age'] > 40]

      Name  Age     City  Salary
2     Anup   75  Chennai   62000
3  Indrani   70   Mumbai   85000

In [50]:
# I only want to see those people whose age is above 40, and their city must be Mumbai
dflist[(dflist['Age'] > 40) & (dflist['City'] == 'Mumbai')]

      Name  Age    City  Salary
3  Indrani   70  Mumbai   85000