In [1]:
import numpy as np
import pandas as pd

## Merging 2 DataFrames

In [12]:
employees = pd.DataFrame({
    'employee_id' : [1, 2, 3, 4, 5],
    'name' : ['Arijit', 'Pallabi', 'Anup', 'Indrani', 'Aditish'],
    'department' : ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id' : [1, 2, 3, 6, 7],
    'salary' : [60000, 80000, 65000, 70000, 90000],
    'bonus' : [5000, 10000, 7000, 8000, 12000]
})

In [13]:
employees

   employee_id     name department
0            1   Arijit         HR
1            2  Pallabi         IT
2            3     Anup    Finance
3            4  Indrani         IT
4            5  Aditish         HR

In [14]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [15]:
pd.merge(employees, salaries)

   employee_id     name department  salary  bonus
0            1   Arijit         HR   60000   5000
1            2  Pallabi         IT   80000  10000
2            3     Anup    Finance   65000   7000

In [16]:
pd.merge(employees, salaries, on='employee_id') # on means common column name

   employee_id     name department  salary  bonus
0            1   Arijit         HR   60000   5000
1            2  Pallabi         IT   80000  10000
2            3     Anup    Finance   65000   7000

In [17]:
pd.merge(employees, salaries, on='employee_id', how='inner') # how inner means common of the two dataframes

   employee_id     name department  salary  bonus
0            1   Arijit         HR   60000   5000
1            2  Pallabi         IT   80000  10000
2            3     Anup    Finance   65000   7000

In [18]:
pd.merge(employees, salaries, on='employee_id', how='outer') # how outer means all of the two dataframes

   employee_id     name department   salary    bonus
0            1   Arijit         HR  60000.0   5000.0
1            2  Pallabi         IT  80000.0  10000.0
2            3     Anup    Finance  65000.0   7000.0
3            4  Indrani         IT      NaN      NaN
4            5  Aditish         HR      NaN      NaN
5            6      NaN        NaN  70000.0   8000.0
6            7      NaN        NaN  90000.0  12000.0

In [19]:
pd.merge(employees, salaries, on='employee_id', how='left') # how left means all of the data takes from left dataframe

   employee_id     name department   salary    bonus
0            1   Arijit         HR  60000.0   5000.0
1            2  Pallabi         IT  80000.0  10000.0
2            3     Anup    Finance  65000.0   7000.0
3            4  Indrani         IT      NaN      NaN
4            5  Aditish         HR      NaN      NaN

In [20]:
pd.merge(employees, salaries, on='employee_id', how='right') # how right means all of the data takes from right dataframe

   employee_id     name department  salary  bonus
0            1   Arijit         HR   60000   5000
1            2  Pallabi         IT   80000  10000
2            3     Anup    Finance   65000   7000
3            6      NaN        NaN   70000   8000
4            7      NaN        NaN   90000  12000

## Concatination Of 2 DataFrames

In [22]:
df1 = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2'],
    'B' : ['B0', 'B1', 'B2'],
    'C' : ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A' : ['A3', 'A4', 'A5'],
    'B' : ['B3', 'B4', 'B5'],
    'C' : ['C3', 'C4', 'C5']
})

In [23]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [24]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [27]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## Joing Of 2 DataFrames

In [30]:
df1 = pd.DataFrame({
    'name' : ['Arijit', 'Pallabi', 'Anup', 'Indrani']
}, index=[1,2,3,4])
df2 = pd.DataFrame({
    'score' : [85, 90, 75, 80]
}, index=[2,3,4,5])

In [31]:
df1

      name
1   Arijit
2  Pallabi
3     Anup
4  Indrani

In [32]:
df2

   score
2     85
3     90
4     75
5     80

In [33]:
df1.join(df2)

      name  score
1   Arijit    NaN
2  Pallabi   85.0
3     Anup   90.0
4  Indrani   75.0

In [34]:
df1.join(df2, how='outer')

      name  score
1   Arijit    NaN
2  Pallabi   85.0
3     Anup   90.0
4  Indrani   75.0
5      NaN   80.0

In [35]:
df1.join(df2, how='inner')

      name  score
2  Pallabi     85
3     Anup     90
4  Indrani     75

In [36]:
df1.join(df2, how='left')

      name  score
1   Arijit    NaN
2  Pallabi   85.0
3     Anup   90.0
4  Indrani   75.0

In [37]:
df1.join(df2, how='right')

      name  score
2  Pallabi     85
3     Anup     90
4  Indrani     75
5      NaN     80

In [38]:
df2.join(df1)

   score     name
2     85  Pallabi
3     90     Anup
4     75  Indrani
5     80      NaN

In [39]:
df2.join(df1, how='outer')

   score     name
1    NaN   Arijit
2   85.0  Pallabi
3   90.0     Anup
4   75.0  Indrani
5   80.0      NaN

In [40]:
df2.join(df1, how='inner')

   score     name
2     85  Pallabi
3     90     Anup
4     75  Indrani

In [41]:
df2.join(df1, how='left')

   score     name
2     85  Pallabi
3     90     Anup
4     75  Indrani
5     80      NaN

In [42]:
df2.join(df1, how='right')

   score     name
1    NaN   Arijit
2   85.0  Pallabi
3   90.0     Anup
4   75.0  Indrani